### ISSUE TITLE
cannot create / edit entries

### ISSUE THREAD

**Issue by iangilmour** [litnimax/astconfman#37]
The Server starts up ok. I can login using the default admin/admin user and view the data, and all looks fine, etc.

But when I try to edit an existing entry or create a new entry it fails with output similar to the following. The log output was generated when I tried to create a new conference room. I get similar errors when I try to add a new user/role or participant/contact

(n.b. I had SQLALCHEMY_ECHO set to True below, but get the same error if it is False).

Browser shows "Internal server error".

```
2018-01-19 15:55:38,834 INFO sqlalchemy.engine.base.Engine (1,)
2018-01-19 15:55:39,010 INFO sqlalchemy.engine.base.Engine SELECT conference_profile.id AS conference_profile_id, conference_profile.name AS conference_profile_name, conference_profile.max_members AS conference_profile_max_members, conference_profile.record_conference AS conference_profile_record_conference, conference_profile.internal_sample_rate AS conference_profile_internal_sample_rate, conference_profile.mixing_interval AS conference_profile_mixing_interval, conference_profile.video_mode AS conference_profile_video_mode, conference_profile.user_id AS conference_profile_user_id 
FROM conference_profile
2018-01-19 15:55:39,018 INFO sqlalchemy.engine.base.Engine ()
Traceback (most recent call last):
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 935, in handle_one_response
    self.run_application()
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 908, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/model/base.py", line 1702, in create_view
    return_url=return_url)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/base.py", line 299, in render
    return render_template(template, **kwargs)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/src/astconfman-origin/astconfman/templates/conference_create.html", line 7, in top-level template code
    {%- trans -%}
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 6, in top-level template code
    <input name="_continue_editing" type="submit" class="btn btn-default" value="{{ _gettext('Save and Continue Editing') }}" />
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/home/user/src/astconfman-origin/astconfman/templates/my_master.html", line 1, in top-level template code
    {% extends 'admin/base.html' %}
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 30, in top-level template code
    {% block page_body %}
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 69, in block "page_body"
    {% block body %}{% endblock %}
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 26, in block "body"
    {{ lib.render_form(form, return_url, extra(), form_opts) }}
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 202, in template
    {% call form_tag(action=action) %}
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 182, in template
    {{ caller() }}
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 203, in template
    {{ render_form_fields(form, form_opts=form_opts) }}
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 166, in template
    {{ r(form, form_opts=form_opts) }}
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/form/rules.py", line 109, in __call__
    result.append(r(form, form_opts, field_args))
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/form/rules.py", line 316, in __call__
    return super(Field, self).__call__(form, form_opts, params)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/form/rules.py", line 208, in __call__
    return macro(**opts)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 130, in template
    {{ field(**kwargs)|safe }}
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/form/widgets.py", line 28, in __call__
    return super(Select2Widget, self).__call__(field, **kwargs)
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/wtforms/widgets/core.py", line 287, in __call__
    for val, label, selected in field.iter_choices():
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/contrib/sqla/fields.py", line 106, in iter_choices
    for pk, obj in self._get_object_list():
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/contrib/sqla/fields.py", line 99, in _get_object_list
    self._object_list = [(text_type(get_pk(obj)), obj) for obj in query]
  File "/home/user/src/astconfman-origin/env/local/lib/python2.7/site-packages/flask_admin/contrib/sqla/fields.py", line 255, in get_pk_from_identity
    cls, key = identity_key(instance=obj)
ValueError: too many values to unpack
Fri Jan 19 15:55:39 2018 {'REMOTE_PORT': '56592', 'HTTP_HOST': 'localhost:5000', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 25)} failed with ValueError

127.0.0.1 - - [2018-01-19 15:55:39] "GET /admin/conference/new/?url=%2Fadmin%2Fconference%2F HTTP/1.1" 500 161 0.328541
```

**Comment by iangilmour** [comment]
Answering my own issue...

Editing requirements.txt and specifying the SQLAlchemy version explicitely fixed my immediate problem.

i.e.

```
SQLAlchemy==1.2.0b3
```
