### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by drnuriev** [litnimax/astconfman#51]
You are using pip version 9.0.1, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env) [root@asterisk-main astconfman]# cd astconfman
(env) [root@asterisk-main astconfman]# ./manage.py init
Traceback (most recent call last):
  File "./manage.py", line 6, in <module>
    from flask_security import utils
  File "/var/www/html/astconfman/astconfman/env/lib/python2.7/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/var/www/html/astconfman/astconfman/env/lib/python2.7/site-packages/flask_security/core.py", line 28, in <module>
    from .forms import ChangePasswordForm, ConfirmRegisterForm, \
  File "/var/www/html/astconfman/astconfman/env/lib/python2.7/site-packages/flask_security/forms.py", line 69, in <module>
    email_validator = Email(message='INVALID_EMAIL_ADDRESS')
  File "/var/www/html/astconfman/astconfman/env/lib/python2.7/site-packages/wtforms/validators.py", line 332, in __init__
    raise Exception("Install 'email_validator' for email validation support.")
Exception: Install 'email_validator' for email validation support.
(env) [root@asterisk-main astconfman]# ./run.py
Traceback (most recent call last):
  File "./run.py", line 4, in <module>
    from app import app
  File "/var/www/html/astconfman/astconfman/app.py", line 12, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore, \
  File "/var/www/html/astconfman/astconfman/env/lib/python2.7/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/var/www/html/astconfman/astconfman/env/lib/python2.7/site-packages/flask_security/core.py", line 28, in <module>
    from .forms import ChangePasswordForm, ConfirmRegisterForm, \
  File "/var/www/html/astconfman/astconfman/env/lib/python2.7/site-packages/flask_security/forms.py", line 69, in <module>
    email_validator = Email(message='INVALID_EMAIL_ADDRESS')
  File "/var/www/html/astconfman/astconfman/env/lib/python2.7/site-packages/wtforms/validators.py", line 332, in __init__
    raise Exception("Install 'email_validator' for email validation support.")
Exception: Install 'email_validator' for email validation support.
(env) [root@asterisk-main astconfman]#

На адрес http://192.168.3.23:5000/ не идет

**Comment by MMMNikolay** [comment]
Доброго времени суток!
У меня аналогичная ситуация. Вы ее победили? Усли да поделитесь

**Comment by rau-alvin** [comment]
Привет! Вам нужно установить мудуль из pip с названием email_validator:

# pip install email_validator
