### ISSUE TITLE
Не работает вкладка confernces

### ISSUE THREAD

**Issue by smazharov** [litnimax/astconfman#55]
Добрый день. При попытке открыть вкладку confernces - confernces выдает Internal Server Error.
В логах выдает следующее:
192.168.1.103 - - [2021-04-15 08:52:10] "GET /admin/participants/ HTTP/1.1" 200 38637 0.636553
[2021-04-15 08:52:15,000] ERROR in app: Exception on /admin/conference/ [GET]
Traceback (most recent call last):
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/model/base.py", line 1655, in index_view
    return_url=self._get_list_url(view_args),
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/base.py", line 299, in render
    return render_template(template, **kwargs)
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/model/list.html", line 5, in top-level template code
    {% import 'admin/actions.html' as actionlib with context %}
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/home/astmin/astconfman/astconfman/templates/my_master.html", line 1, in top-level template code
    {% extends 'admin/base.html' %}
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 30, in top-level template code
    {% block page_body %}
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 69, in block "page_body"
    {% block body %}{% endblock %}
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/model/list.html", line 54, in block "body"
    {% block model_list_table %}
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/model/list.html", line 100, in block "model_list_table"
    {% block list_row scoped %}
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/templates/bootstrap3/admin/model/list.html", line 153, in block "list_row"
    {{ get_value(row, c) }}
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/model/base.py", line 1512, in get_list_value
    value = self._get_field_value(model, name)
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/model/base.py", line 1494, in _get_field_value
    return rec_getattr(model, name)
  File "/home/astmin/astconfman/env/lib/python2.7/site-packages/flask_admin/tools.py", line 81, in rec_getattr
    return reduce(getattr, attr.split('.'), obj)
  File "/home/astmin/astconfman/astconfman/models.py", line 64, in _is_locked
    return asterisk.confbridge_is_locked(self.number)
  File "/home/astmin/astconfman/astconfman/asterisk.py", line 152, in confbridge_is_locked
    return confbridge_get(confno)['locked']
  File "/home/astmin/astconfman/astconfman/asterisk.py", line 128, in confbridge_get
    output = _cli_command('confbridge list')
  File "/home/astmin/astconfman/astconfman/asterisk.py", line 21, in _cli_command
    raise Exception(output)
Exception: Unable to connect to remote asterisk (does /var/run/asterisk/asterisk.ctl exist?)
192.168.1.103 - - [2021-04-15 08:52:15] "GET /admin/conference/ HTTP/1.1" 500 426 0.065050

Кто нибудь с подобным сталкивался? Спасибо.

**Comment by niaproxy** [comment]
> Exception: Unable to connect to remote asterisk (does /var/run/asterisk/asterisk.ctl exist?)

Запускай run.py от юзера с которым работает Asterisk.
